language: go
sudo: false

addons:
        apt:
                packages:
                        - libgeoip-dev
                        - geoip-database

go:
        - 1.9.x
        - 1.10.x
        - 1.11.x
        - tip
