language: go
sudo: false

addons:
        apt:
                packages:
                        - libgeoip-dev
                        - geoip-database

go:
        - 1.5
        - 1.6
        - tip
